---
- name: Installing frontend webserver with mod_cluster
  hosts: webservers
  become: true
  remote_user: user
  vars:
    temp_path: /tmp
  roles:
  - httpd

- name: Installing Jboss EAP
  hosts: eap
  become: true
  remote_user: user
  vars:
    temp_path: /tmp
  roles:
  - eap
  
- name: Configure EAP domain
  hosts: eap-domains
  become: true
  remote_user: user
  vars:
    temp_path: /tmp
  roles:
  - eap-domain
  
- name: Configuring EAP nodes
  hosts: eap-nodes
  become: true
  remote_user: user
  vars:
    temp_path: /tmp
  roles:
  - eap-node
  
