---
# tasks file for roles/httpd
- name: prereqs
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
  - apr
  - apr-util
  - mailcap

- name: check if installed
  stat:
    path: "{{ jboss_httpd_home }}"
  register: httpd_path

- name: stop apache
  shell: 
    cmd: ./apachectl stop
    chdir: "{{ jboss_httpd_home }}/sbin"
  when: httpd_path.stat.exists
  ignore_errors: true

- name: add apache group
  group:
    name: apache
    gid: 48

- name: add apache user
  user: 
    name: apache
    uid: 48
    group: apache
    shell: /bin/sh

- name: download file
  get_url:
    url: "{{ binary_location }}/{{ jboss_httpd_binary }}" 
    dest: "{{ temp_path }}/{{ jboss_httpd_binary }}"
    
- name: unarchive httpd
  unarchive:
    src: "{{ temp_path }}/{{ jboss_httpd_binary }}"
    copy: false
    dest: "{{ httpd_pre_path }}"
    owner: apache
    group: apache
    
- name: run post install
  shell: 
    cmd: ./.postinstall
    chdir: "{{ jboss_httpd_home }}"

- name: copy mod_cluster.conf
  copy:
    src: mod_cluster.conf
    dest: "{{ jboss_httpd_home }}/conf.d/mod_cluster.conf"

- name: copy httpd.conf
  copy:
    src: httpd.conf
    dest: "{{ jboss_httpd_home }}/conf/httpd.conf"
  notify:
  - start apache
  